# docker-compose.override.yml
# version: "3.9"

services:
  app:
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      BUILD_ASSETS: "false"        # unterdrückt Prod-Build im Entrypoint
      FORCE_ASSETS_BUILD: "false"  # sicherheitshalber, falls geprüft wird
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"   # Laravel/Apache erreichbar unter http://localhost:8080

  vite:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: sh -lc "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173" # Vite-Dev-Server (HMR)
    depends_on:
      - app
